services:
  llm-sm:
    image: ${LDS_LLM_IMAGE:-infocyph/llm-sm:latest}
    restart: unless-stopped
    profiles: [ai]
    volumes:
      - lds_llm:/root/.ollama
    networks:
      - frontend
      - backend
