services:
  nginx:
    container_name: NGINX
    hostname: nginx
    image: infocyph/nginx:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ:-}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ../../logs/nginx:/var/log/nginx
      - lds_nginx_host:/etc/nginx/conf.d:ro
      - lds_ssl_keys:/etc/mkcert:ro
      - lds_ssl_roots:/etc/share/rootCA:ro
      - "${PROJECT_DIR:-./../../../application}:/app"
      - lds_fpm_sock:/run/php-fpm:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      frontend:
        ipv4_address: 172.28.0.10
    depends_on:
      - server-tools

  apache:
    container_name: APACHE
    hostname: apache
    image: infocyph/apache:latest
    restart: always
    profiles:
      - apache
    environment:
      - TZ=${TZ:-}
    volumes:
      - lds_ssl_keys:/etc/mkcert:ro
      - lds_apache_host:/usr/local/apache2/conf/extra:ro
      - ../../logs/apache:/var/log/apache2
      - lds_ssl_roots:/etc/share/rootCA:ro
      - "${PROJECT_DIR:-./../../../application}:/app"
      - lds_fpm_sock:/run/php-fpm:ro
    depends_on:
      - nginx
    networks:
      frontend:
        ipv4_address: 172.28.0.11
